[workspace]

members = [
    "sample_projects/truffle_overview",
    "sample_projects/async_sample",
    "truffle",
    "truffle-attributes",
    "truffle-lsp",
]

resolver = "2"

[profile.release]
debug = true
